# permissions for end users to edit initcontainerinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deployment-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: initcontainerinjector-editor-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - initcontainerinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - initcontainerinjectors/status
  verbs:
  - get
