# permissions for end users to view initcontainerinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deployment-injector-operator
    app.kubernetes.io/managed-by: kustomize
  name: initcontainerinjector-viewer-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - initcontainerinjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - initcontainerinjectors/status
  verbs:
  - get
